openapi: 3.0.0
info:
  title: TODO-API
  version: 1.0.0
  components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  description: Documentation for TODO-API

servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
